### ISSUE TITLE
El modulo USIG es abierto? Donde está el código? 

### ISSUE THREAD

**Issue by avilaton** [gcba/BA-Como-Llego#3]
En la carpeta vendor hay un módulo que hace los queries. Solo lo encontré minificado. Esta disponible en algún otro lado? 
Gracias!

**Comment by Jinik** [comment]
@avilaton Los servicios de USIG [están disponibles acá](http://servicios.usig.buenosaires.gob.ar/usig-js/) con la documentación y ejemplos. En el prototipo estamos usando la versión 3.1.

**Comment by avilaton** [comment]
:+1: gracias
